// Re-export WS types from shared package — canonical source is @protoimsg/shared
export type {
  WsMessageBase,
  StatusChangeMessage,
  PingMessage,
  RequestCommunityPresenceMessage,
  AuthMessage,
  DmOpenMessage,
  DmCloseMessage,
  ImOfferMessage,
  ImAnswerMessage,
  ImIceCandidateMessage,
  SyncBlocksMessage,
  ClientMessage,
  PresenceUpdateEvent,
  CommunityPresenceEvent,
  PongEvent,
  ErrorEvent,
  DmOpenedEvent,
  ImOfferEvent,
  ImAnswerEvent,
  ImIceCandidateEvent,
  ServerMessage,
} from '@protoimsg/shared';
