/** Stable error codes shared between server and client for i18n translation. */
export const ERROR_CODES = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_SESSION: 'INVALID_SESSION',
  INVALID_CHALLENGE: 'INVALID_CHALLENGE',
  HANDLE_MISMATCH: 'HANDLE_MISMATCH',
  AUTH_VERIFICATION_FAILED: 'AUTH_VERIFICATION_FAILED',
  AUTH_TIMEOUT: 'AUTH_TIMEOUT',
  AUTH_REQUIRED: 'AUTH_REQUIRED',

  // Access control
  FORBIDDEN: 'FORBIDDEN',
  BANNED: 'BANNED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  NOT_PARTICIPANT: 'NOT_PARTICIPANT',
  BLOCKED_USER: 'BLOCKED_USER',
  SELF_DM: 'SELF_DM',

  // Validation
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_JSON: 'INVALID_JSON',
  INVALID_MESSAGE_FORMAT: 'INVALID_MESSAGE_FORMAT',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  CONTENT_FILTERED: 'CONTENT_FILTERED',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',

  // Translation
  TRANSLATE_RATE_LIMITED: 'TRANSLATE_RATE_LIMITED',
  TRANSLATE_UNAVAILABLE: 'TRANSLATE_UNAVAILABLE',

  // Server
  SERVER_ERROR: 'SERVER_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
